### ISSUE TITLE
License for TSQL-Smells

### ISSUE THREAD

**Issue by damien-johnston** [davebally/TSQL-Smells#5]
What is the license for this project and code? I'd like to use it as a base for a project at work to implement SCA on our database project, is a license required to do this or are you giving full rights to individuals to modify and use as they see fit?

TIA,

Damien

**Comment by Ozzie** [comment]
Red-Gate might have adopted a lot of these in its new free app SQL Code Guard - https://documentation.red-gate.com/display/SCG/Installing?_ga=2.77906002.794375549.1508878608-125739661.1508878608

**Comment by spakh** [comment]
Please be aware SQL Code Guard currently only runs under SSMS 2016 which only runs in Windows 8.1 and above. We are still on Windows 7 in our corporate world and can't use the product. Also, seeing how Red-Gate develops their tools, I would not be surprised if this product eventually loses its gratis feature.

**Comment by arvindsh** [comment]
Hello @davebally could you please add a LICENSE file to this repo so as to formally indicate your position on this?
